<?php

namespace App\Http\Controllers\System\systemConfig;
use App\Http\Controllers\System\ResourceController;
use App\Services\System\ConfigService;

class configController extends ResourceController
{
    public function __construct(ConfigService $configService){
        parent::__construct($configService);
    }

    public function storeValidationRequest()
    {
        return 'App\Http\Requests\system\ConfigRequest';
    }

    public function moduleName(){
        return 'configs';
    }

    public function viewFolder()
    {
        return 'system.config';
    }

    public function update($id)
    {
        if (!isSameCompany($id, RESOURCE_TYPE[3])){
            return redirect($this->getUrl())->withErrors(['alert-danger' => translate(NO_ACCESS_MSG)]);
        }
        return parent::update($id); // TODO: Change the autogenerated stub
    }
}
