<?php

namespace App\Http\Controllers\System\systemConfig;

use App\Http\Controllers\System\ResourceController;
use App\Services\System\EmailTemplateService;

class emailTemplateController extends ResourceController
{
    public function __construct(EmailTemplateService $emailtemplateService){
       parent::__construct($emailtemplateService);
    }

    public function storeValidationRequest()
    {
        return 'App\Http\Requests\system\emailTemplateRequest';
    }

    public function moduleName(){
        return 'email-templates';
    }

    public function viewFolder()
    {
        return 'system.email-template';
    }
    public function update($id)
    {
        if (!isSameCompany($id, RESOURCE_TYPE[2])){
            return redirect($this->getUrl())->withErrors(['alert-danger' => translate('unauthorized!!!')]);
        }
        return parent::update($id); // TODO: Change the autogenerated stub
    }
}
